// Copyright PolyAI Limited

import Foundation

enum WireEventType: String {
    case heartbeat = "EVENT_TYPE_HEARTBEAT"
    case sessionStart = "EVENT_TYPE_SESSION_START"
    case sessionEnd = "EVENT_TYPE_SESSION_END"
    case userMessage = "EVENT_TYPE_USER_MESSAGE"
    case userTyping = "EVENT_TYPE_USER_TYPING"
    case userEndSession = "EVENT_TYPE_USER_END_SESSION"
    case requestPolyAgentJoin = "EVENT_TYPE_REQUEST_POLY_AGENT_JOIN"
    case polyAgentJoined = "EVENT_TYPE_POLY_AGENT_JOINED"
    case polyAgentThinking = "EVENT_TYPE_POLY_AGENT_THINKING"
    case polyAgentMessage = "EVENT_TYPE_POLY_AGENT_MESSAGE"
    case polyAgentMessageChunk = "EVENT_TYPE_POLY_AGENT_MESSAGE_CHUNK"
    case polyAgentLeft = "EVENT_TYPE_POLY_AGENT_LEFT"
    case polyAgentTriggeredHandoff = "EVENT_TYPE_POLY_AGENT_TRIGGERED_HANDOFF"
    case liveAgentJoined = "EVENT_TYPE_LIVE_AGENT_JOINED"
    case liveAgentTyping = "EVENT_TYPE_LIVE_AGENT_TYPING"
    case liveAgentMessage = "EVENT_TYPE_LIVE_AGENT_MESSAGE"
    case liveAgentLeft = "EVENT_TYPE_LIVE_AGENT_LEFT"
    case systemMessage = "EVENT_TYPE_SYSTEM_MESSAGE"
    case clientHandoffRequired = "EVENT_TYPE_CLIENT_HANDOFF_REQUIRED"
    case handoffQueueStatus = "EVENT_TYPE_HANDOFF_QUEUE_STATUS"
    case handoffAccepted = "EVENT_TYPE_HANDOFF_ACCEPTED"
    case handoffFailed = "EVENT_TYPE_HANDOFF_FAILED"
    case handoffTimeout = "EVENT_TYPE_HANDOFF_TIMEOUT"
    case eventBatch = "EVENT_TYPE_EVENT_BATCH"
    case sessionIdleWarning = "EVENT_TYPE_SESSION_IDLE_WARNING"
    case userReceivedMessage = "EVENT_TYPE_USER_RECEIVED_MESSAGE"
    case userReadMessage = "EVENT_TYPE_USER_READ_MESSAGE"
    case polyAgentReceivedMessage = "EVENT_TYPE_POLY_AGENT_RECEIVED_MESSAGE"
    case polyAgentReadMessage = "EVENT_TYPE_POLY_AGENT_READ_MESSAGE"
    case liveAgentReceivedMessage = "EVENT_TYPE_LIVE_AGENT_RECEIVED_MESSAGE"
    case liveAgentReadMessage = "EVENT_TYPE_LIVE_AGENT_READ_MESSAGE"
    case showCsatRequest = "EVENT_TYPE_SHOW_CSAT_REQUEST"
    case csatResponse = "EVENT_TYPE_CSAT_RESPONSE"
}
